### ISSUE TITLE
Usage with docker compose

### ISSUE THREAD

**Issue by galah92** [adinhodovic/rabbitmq-mixin#2]
Hi @adinhodovic, thank you very much for creating this. I'm trying to make this work from docker compose, how should I configure the scraping of `/metrics/detailed`? I tried to do it with the following code in `prometheus.yml`, but that API endpoint still return 404:
```yml
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics/detailed
    params:
      family:
      - queue_coarse_metrics
      - queue_consumer_count
```

Thanks
