### ISSUE TITLE
Specific port?

### ISSUE THREAD

**Issue by GuillaumeCisco** [adinhodovic/rabbitmq-mixin#3]
From the service-monitor declaration, there is this part:
```
path: /metrics/detailed
port: metrics
```

What is the port `metrics`, is it defined somewhere or is it by default?

I struggle running your work in addition to https://hodovi.cc/blog/rabbitmq-per-queue-monitoring/
I think it might come from a wrong port declaration...

**Comment by adinhodovic** [comment]
Hey,

The [bitnami rabbitmq chart](https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq) exposes metrics on port 9419, however this is configured by Bitnami. I believe the default Prometheus port in all other setups is 15672. The service that comes with the helm chart has the port name "metrics" mapped to 9419.

```
  - name: metrics
    port: 9419
    protocol: TCP
    targetPort: metrics
```

**Comment by GuillaumeCisco** [comment]
From every tutorials I see, it looks like it is the classic web http port `9090` for prometheus not rabbitmq

https://grafana.com/docs/grafana-cloud/monitor-infrastructure/kubernetes-monitoring/configuration/configure-infrastructure-manually/prometheus/prometheus-operator/
https://observability.thomasriley.co.uk/prometheus/configuring-prometheus/using-service-monitors/

But I am confused now...

**Comment by adinhodovic** [comment]
Prometheus has it's own port, but prometheus needs to scrape other services to "pull" metrics. RabbitMQ exports metrics on their own port of 15672 or 9419.

**Comment by GuillaumeCisco** [comment]
Ok so I think I am mixing things.
Tell me if I am correct.
rabbitmq-mixin needs a service monitor on rabbitmq exposing the prometheus plugin, but does not link to the prometheus services.pods.
If yes, this where I am struggling to understand how it can works, as we are defining the new rule on prometheus, but looks like we are not binding it to anything with our new service monitor.

And from the other tutorials I gave, it is actually setting a service monitor to the actual deployed prometheus service.
Is that correct?

**Comment by adinhodovic** [comment]
> Ok so I think I am mixing things. Tell me if I am correct. rabbitmq-mixin needs a service monitor on rabbitmq exposing the prometheus plugin, but does not link to the prometheus services.pods. If yes, this where I am struggling to understand how it can works, as we are defining the new rule on prometheus, but looks like we are not binding it to anything with our new service monitor.
> 
> And from the other tutorials I gave, it is actually setting a service monitor to the actual deployed prometheus service. Is that correct?

> rabbitmq-mixin needs a service monitor on rabbitmq exposing the prometheus plugin, but does not link to the prometheus services.pods.
Rabbitmq-mixin needs metrics in the prometheus instance to visualize dashboards and alerts. A service monitor is defined to tell prometheus  from where to scrape the metrics. (Scrape it from the rabbitmq service/pods on this port). You can use the prometheus operator (that handles the service monitor) to configure your prometheus instance or just have bare configs. It depends on your setup.

**Comment by GuillaumeCisco** [comment]
Thanks for additional information.
Feels better now. I was struggling understanding how everything is connected.
And from different tutorials it is even more misleading. Especially the service monitoring part.

Will give it a try :+1:

**Comment by GuillaumeCisco** [comment]
Ok no success :/

But I think it is better than before now... I get new data.
Looks like the only missing thing is a configuration communication for getting the data returned by the rule.

I know github repository issues are not a support forum.
But if you see an error at first sight, it will really help me :)

I am deploying my rabbitmq cluster thanks to helm
The Dockerfile for rabbitmq exposes ports:
```
FROM rabbitmq:3.12.4-management

...
COPY ./rabbitmq.config /etc/rabbitmq/rabbitmq.config
...

EXPOSE 4369 5671 5672 25672 15671 15672 15692 9419
```
the erlang config used is `rabbitmq.config`:
```
[
    { rabbit, [
            { consumer_timeout, 86580000 },
            { loopback_users, [ ] },
            { tcp_listeners, [ 5672 ] },
            { ssl_listeners, [ ] },
            { hipe_compile, false },
            { cluster_partition_handling, pause_minority},
            { vm_memory_high_watermark_paging_ratio, 0.99},
            { disk_free_limit, [{ absolute, 1000000000}] },
            { collect_statistics_interval, 10000}
    ] },
    { rabbitmq_management, [ { listener, [
            { port, 15672 },
            { ssl, false }
    ] } ] }
].
```

the service is defined as:
```
apiVersion: v1
kind: Service
metadata:
  name: {{ include "broker.fullname" . }}
  labels:
    {{- include "broker.labels" . | nindent 4 }}
spec:
  ports:
  - port: 4369
    name: rabbitmq-epmd
  - port: 5672
    name: rabbitmq-main
  - port: 15672
    name: rabbitmq-management
  - port: 15692
    name: rabbitmq-prometheus
  - port: 25672
    name: rabbitmq-management-ssl
  - port: 9419
    name: rabbitmq-metrics
  clusterIP: None
  selector:
    {{- include "broker.selectorLabels" . | nindent 4 }}
```

The ServiceMonitor as:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "broker.fullname" . }}
  labels:
    {{- include "broker.labels" . | nindent 4 }}
spec:
  endpoints:
  - interval: 30s
    params:
      family:
      - queue_coarse_metrics
      - queue_consumer_count
    path: /metrics/detailed
    port: rabbitmq-metrics
  namespaceSelector:
    matchNames:
      - <censored_for_enterprise_confidential_reason>
  selector:
    matchLabels:
      {{- include "broker.selectorLabels" . | nindent 4 }}
```

For prometheus, I declared a rule file `rabbitmq_queue_info.yml` with content:
```
groups:
  - name: rabbitmq.rules
    rules:
    - record: rabbitmq_queue_info
      expr: rabbitmq_detailed_queue_consumers * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info
```

When launching: `kubectl port-forward svc/prometheus -n censored 9090:9090`
I can see targets, configuration and rules that looks ok:
![Screenshot_2023-09-06_16-53-51](https://github.com/adinhodovic/rabbitmq-mixin/assets/1155244/f995ec9c-d9a6-45b2-b6c4-a01c35d055b4)
![Screenshot_2023-09-06_16-54-31](https://github.com/adinhodovic/rabbitmq-mixin/assets/1155244/ed63b7b9-4d11-419c-9a77-d891005a0009)
![Screenshot_2023-09-06_17-39-20](https://github.com/adinhodovic/rabbitmq-mixin/assets/1155244/ed3b7dec-da6e-4d6f-91e4-6a9fa4dc8748)



For grafana, when launching: `kubectl port-forward svc/grafana -n censored 3000:3000`
I get no results :/

![Screenshot_2023-09-06_16-54-48](https://github.com/adinhodovic/rabbitmq-mixin/assets/1155244/5f61f7b4-b0db-4a2b-9489-147a0ac9b355)

Impossible to display vhosts or queues.
I have some when looking at the basic `rabbitmq-management` on `15672`

I don't see any error in the pod logs (maybe wrong log level?)

prometheus displays:
```
| ts=2023-09-06T14:01:07.535Z caller=main.go:534 level=info msg="No time or size retention was set so using the default time retention" duration=15d                                                                                        │
│ ts=2023-09-06T14:01:07.535Z caller=main.go:578 level=info msg="Starting Prometheus Server" mode=server version="(version=2.45.0, branch=HEAD, revision=8ef767e396bf8445f009f945b0162fd71827f445)"                                         │
│ ts=2023-09-06T14:01:07.535Z caller=main.go:583 level=info build_context="(go=go1.20.5, platform=linux/amd64, user=root@920118f645b7, date=20230623-15:09:49, tags=netgo,builtinassets,stringlabels)"                                      │
│ ts=2023-09-06T14:01:07.535Z caller=main.go:584 level=info host_details="(Linux 5.15.107+ #1 SMP Thu Jun 15 09:51:46 UTC 2023 x86_64 prometheus-5fc9f5cdfb-f28zs (none))"                                                                  │
│ ts=2023-09-06T14:01:07.535Z caller=main.go:585 level=info fd_limits="(soft=1048576, hard=1048576)"                                                                                                                                        │
│ ts=2023-09-06T14:01:07.535Z caller=main.go:586 level=info vm_limits="(soft=unlimited, hard=unlimited)"                                                                                                                                    │
│ ts=2023-09-06T14:01:07.595Z caller=web.go:562 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090                                                                                                         │
│ ts=2023-09-06T14:01:07.597Z caller=main.go:1019 level=info msg="Starting TSDB ..."                                                                                                                                                        │
│ ts=2023-09-06T14:01:07.601Z caller=tls_config.go:274 level=info component=web msg="Listening on" address=:9090                                                                                                                            │
│ ts=2023-09-06T14:01:07.601Z caller=tls_config.go:277 level=info component=web msg="TLS is disabled." http2=false address=:9090                                                                                                            │
│ ts=2023-09-06T14:01:07.607Z caller=head.go:595 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"                                                                                                            │
│ ts=2023-09-06T14:01:07.608Z caller=head.go:676 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=35.637µs                                                                                          │
│ ts=2023-09-06T14:01:07.608Z caller=head.go:684 level=info component=tsdb msg="Replaying WAL, this may take a while"                                                                                                                       │
│ ts=2023-09-06T14:01:07.609Z caller=head.go:755 level=info component=tsdb msg="WAL segment loaded" segment=0 maxSegment=0                                                                                                                  │
│ ts=2023-09-06T14:01:07.609Z caller=head.go:792 level=info component=tsdb msg="WAL replay completed" checkpoint_replay_duration=181.212µs wal_replay_duration=924.333µs wbl_replay_duration=262ns total_replay_duration=1.442706ms         │
│ ts=2023-09-06T14:01:07.612Z caller=main.go:1040 level=info fs_type=EXT4_SUPER_MAGIC                                                                                                                                                       │
│ ts=2023-09-06T14:01:07.612Z caller=main.go:1043 level=info msg="TSDB started"                                                                                                                                                             │
│ ts=2023-09-06T14:01:07.612Z caller=main.go:1224 level=info msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml                                                                                                       │
│ ts=2023-09-06T14:01:07.616Z caller=main.go:1261 level=info msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml totalDuration=4.47882ms db_storage=19.694µs remote_storage=36.213µs web_handler=866ns qu │
│ ts=2023-09-06T14:01:07.617Z caller=main.go:1004 level=info msg="Server is ready to receive web requests."                                                                                                                                 │
│ ts=2023-09-06T14:01:07.617Z caller=manager.go:995 level=info component="rule manager" msg="Starting rule manager..."
```

Maybe the port is not the right one.
But looks like `9419` is the one to go with, if I am following your tutorial. I also tried with `15672` or `15692` without success.
What is interesting though is that requesting `http://localhost:15692/metrics/detailed?vhost=<censored>&family=queue_coarse_metrics&family=queue_consumer_count`
gives me data but `rabbitmq_queue_info` is not present, only `rabbitmq_identity_info`.
So maybe a service monitoring issue?

Bitnami rabbitmq doc displays:

![Screenshot_2023-09-06_17-01-03](https://github.com/adinhodovic/rabbitmq-mixin/assets/1155244/b58e09bf-e55c-4d16-ba41-00ef19782e02)


Maybe some configurations need also to be added to access /metrics/detailed ?
I am still looking for a solution, but I am starting to give up :/

Any help is appreciated :+1:

**Comment by adinhodovic** [comment]
@GuillaumeCisco the `rabbitmq_queue_info` does not exist in the /metrics/detailed endpoint but is populated by the prometheus rule that is added(that's why I added it). You can maybe portforward your prometheus instance and see if you have the rabbitmq_queue_info metric in the metrics explorer. 

Otherwise see the rule itself in the prometheus UI something like: 
![image](https://github.com/adinhodovic/rabbitmq-mixin/assets/12065867/623a1e7c-f4da-48fa-90ca-549d24470d4e)

Edit: I see you shared the image.

Try pressing on the expression in the rule UI and see if any metrics pop up

**Comment by GuillaumeCisco** [comment]
Ok I was trying thing and discovered I don't get any data for the rule expression...
![Screenshot_2023-09-06_17-47-14](https://github.com/adinhodovic/rabbitmq-mixin/assets/1155244/49d14a92-e492-48f7-83fd-3620e7dff2f2)
![Screenshot_2023-09-06_17-47-27](https://github.com/adinhodovic/rabbitmq-mixin/assets/1155244/2f3794ba-7568-4391-bd26-752328e96f23)


Maybe it comes from this too?

**Comment by adinhodovic** [comment]
Yeah the rule doesn't evaluate to any metrics(it should).Try to see if rabbitmq_detailed_queue_consumers has any metrics.

**Comment by GuillaumeCisco** [comment]
Nothing too

![Screenshot_2023-09-06_19-03-38](https://github.com/adinhodovic/rabbitmq-mixin/assets/1155244/6cd97ee8-50ae-4985-9913-8d9fd745c055)


but on http://localhost:15692/metrics/detailed?vhost=censored_vhost&family=queue_coarse_metrics&family=queue_consumer_count

I get:
```
# TYPE rabbitmq_detailed_queue_consumers gauge
# HELP rabbitmq_detailed_queue_consumers Consumers on a queue
rabbitmq_detailed_queue_consumers{vhost="censored_vhost",queue="celery@worker-7464f44fb-fblsm.celery.pidbox"} 1
```
I am not displaying all my workers, but there are listed

My service monitor definition:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "broker.fullname" . }}
  labels:
    {{- include "broker.labels" . | nindent 4 }}
spec:
  endpoints:
  - interval: 30s
    params:
      family:
      - queue_coarse_metrics
      - queue_consumer_count
    path: /metrics/detailed
    port: rabbitmq-prometheus
  selector:
    matchLabels:
      {{- include "broker.selectorLabels" . | nindent 4 }}
```

with port set to `rabbitmq-prometheus` which is 15692

**Comment by GuillaumeCisco** [comment]
Further information,
On  http://localhost:15692/metrics/detailed?vhost=censored_vhost&family=queue_coarse_metrics&family=queue_consumer_count
I get
```
# TYPE rabbitmq_identity_info untyped
# HELP rabbitmq_identity_info RabbitMQ node & cluster identity info
rabbitmq_identity_info{rabbitmq_node="rabbit@broker-0",rabbitmq_cluster="rabbit@broker-0.broker.<censored>.svc.cluster.local",rabbitmq_cluster_permanent_id="rabbitmq-cluster-id-jp4rF6-9WDmHJInjpKiNTA"} 1
```

Only one line, not the others ones for broker-1 and broker-2 as defined in my previous screen
![Screenshot_2023-09-06_17-47-14](https://github.com/adinhodovic/rabbitmq-mixin/assets/1155244/363a9be7-e234-4886-b688-902544e0c221)


I don't know if it helps.
Maybe I am looking in the wrong direction.

**Comment by adinhodovic** [comment]
@GuillaumeCisco I'm not sure, the metrics are not getting into your prometheus instance.

![image](https://github.com/adinhodovic/rabbitmq-mixin/assets/12065867/0f48ff0e-b893-4e96-a9bc-afb9bdb3d57f)

Also I would expect the following job in your prometheus config: 
![image](https://github.com/adinhodovic/rabbitmq-mixin/assets/12065867/219e616b-d2c3-42fe-afa4-7df1dc50f638)
That would come from the service monitor. The one that you have from static configs comes from static configs, not the service monitor

**Comment by GuillaumeCisco** [comment]
Ok I added:
```
  - job_name: 'prometheus-details'
    static_configs:
      - targets: [ 'localhost:9090' ]
    metrics_path: '/metrics/details'
    params:
      family:
        - 'queue_coarse_metrics'
        - 'queue_consumer_count'
    scrape_interval: '30s'
```
to my prometheus config.
It ended in:
![Screenshot_2023-09-06_19-29-43](https://github.com/adinhodovic/rabbitmq-mixin/assets/1155244/58184fbc-d091-44bc-943e-04ca37f754c7)


But I get same results on expression execution grafana

**Comment by GuillaumeCisco** [comment]
Ok there is an error displayed

Indeed it is the wrong path/port/host
![Screenshot_2023-09-06_19-32-57](https://github.com/adinhodovic/rabbitmq-mixin/assets/1155244/cfb32ae0-f492-4f3c-b92e-526e6e2d1947)


I need to understand how to correctly route this

**Comment by GuillaumeCisco** [comment]
Ok got it finally working by fixing the typo and modifying the targets.
right code is:
```
  - job_name: 'prometheus-details'
    static_configs:
      - targets:
          - 'broker-0.broker.censored.svc.cluster.local:15692'
          - 'broker-1.broker.censored.svc.cluster.local:15692'
          - 'broker-2.broker.censored.svc.cluster.local:15692'
    metrics_path: '/metrics/detailed'
    params:
      family:
        - 'queue_coarse_metrics'
        - 'queue_consumer_count'
    scrape_interval: '30s'
```

![Screenshot_2023-09-06_19-57-03](https://github.com/adinhodovic/rabbitmq-mixin/assets/1155244/eb403d31-e3ad-4261-92f2-8b1600e1cde3)


And now we have a real error for the expression:
![Screenshot_2023-09-06_19-58-36](https://github.com/adinhodovic/rabbitmq-mixin/assets/1155244/30aaefe8-964c-4559-8799-d68625b9b40e)


Looks like it does not works by specifying multiple targets.
Is there a way to achieve this?

**Comment by GuillaumeCisco** [comment]
Ok I finally did it!

Right config for prometheus was:
```
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'rabbitmq-server'
    static_configs:
      - targets:
          - 'broker-0.broker.censored.svc.cluster.local:15692'
          - 'broker-1.broker.censored.svc.cluster.local:15692'
          - 'broker-2.broker.censored.svc.cluster.local:15692'
    metrics_path: '/metrics/detailed'
    params:
      family:
        - 'queue_coarse_metrics'
        - 'queue_consumer_count'
    scrape_interval: '30s'
```

![Screenshot_2023-09-06_21-05-44](https://github.com/adinhodovic/rabbitmq-mixin/assets/1155244/ab096a60-f284-4130-b057-1c8f88ff866f)
![Screenshot_2023-09-06_21-06-09](https://github.com/adinhodovic/rabbitmq-mixin/assets/1155244/f08d8c8e-bf84-4b42-a720-050d060faf33)
![Screenshot_2023-09-06_21-06-48](https://github.com/adinhodovic/rabbitmq-mixin/assets/1155244/75e187e7-078e-46f5-b7a6-929be1923b64)


Thanks a lot for all the help @adinhodovic !!! It helped me so much!!!
